# Generated by Django 5.2 on 2025-04-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/placeholder.png', null=True, upload_to='profile_pics/'),
        ),
    ]
