# Generated by Django 5.2 on 2025-04-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/placeholderuser.png', null=True, upload_to='profile_pics/'),
        ),
    ]
