# Generated by Django 5.1.5 on 2025-04-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiz_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
