# Generated by Django 5.1.5 on 2025-04-16 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quizresult'),
        ('quiz', '0007_quiz_imdb_id'),
    ]

    operations = [
    ]
